/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as JvmRouteImport } from './routes/jvm'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CausalityRouteImport } from './routes/causality'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiopsRouteImport } from './routes/aiops'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesNameRouteImport } from './routes/services.$name'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const JvmRoute = JvmRouteImport.update({
  id: '/jvm',
  path: '/jvm',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalityRoute = CausalityRouteImport.update({
  id: '/causality',
  path: '/causality',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiopsRoute = AiopsRouteImport.update({
  id: '/aiops',
  path: '/aiops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNameRoute = ServicesNameRouteImport.update({
  id: '/services/$name',
  path: '/services/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/jvm': typeof JvmRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/search': typeof SearchRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/jvm': typeof JvmRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/search': typeof SearchRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forecast': typeof ForecastRoute
  '/jvm': typeof JvmRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/search': typeof SearchRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiops'
    | '/alerts'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/forecast'
    | '/jvm'
    | '/logs'
    | '/metrics'
    | '/search'
    | '/topology'
    | '/traces'
    | '/services/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiops'
    | '/alerts'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/forecast'
    | '/jvm'
    | '/logs'
    | '/metrics'
    | '/search'
    | '/topology'
    | '/traces'
    | '/services/$name'
  id:
    | '__root__'
    | '/'
    | '/aiops'
    | '/alerts'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/forecast'
    | '/jvm'
    | '/logs'
    | '/metrics'
    | '/search'
    | '/topology'
    | '/traces'
    | '/services/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiopsRoute: typeof AiopsRoute
  AlertsRoute: typeof AlertsRoute
  CausalityRoute: typeof CausalityRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ForecastRoute: typeof ForecastRoute
  JvmRoute: typeof JvmRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  SearchRoute: typeof SearchRoute
  TopologyRoute: typeof TopologyRoute
  TracesRoute: typeof TracesRoute
  ServicesNameRoute: typeof ServicesNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jvm': {
      id: '/jvm'
      path: '/jvm'
      fullPath: '/jvm'
      preLoaderRoute: typeof JvmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causality': {
      id: '/causality'
      path: '/causality'
      fullPath: '/causality'
      preLoaderRoute: typeof CausalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiops': {
      id: '/aiops'
      path: '/aiops'
      fullPath: '/aiops'
      preLoaderRoute: typeof AiopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$name': {
      id: '/services/$name'
      path: '/services/$name'
      fullPath: '/services/$name'
      preLoaderRoute: typeof ServicesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiopsRoute: AiopsRoute,
  AlertsRoute: AlertsRoute,
  CausalityRoute: CausalityRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ForecastRoute: ForecastRoute,
  JvmRoute: JvmRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  SearchRoute: SearchRoute,
  TopologyRoute: TopologyRoute,
  TracesRoute: TracesRoute,
  ServicesNameRoute: ServicesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
