/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as TraceCompareRouteImport } from './routes/trace-compare'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as TopMoversRouteImport } from './routes/top-movers'
import { Route as SlowSpansRouteImport } from './routes/slow-spans'
import { Route as SloRouteImport } from './routes/slo'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfilingRouteImport } from './routes/profiling'
import { Route as OutliersRouteImport } from './routes/outliers'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LatencyHeatmapRouteImport } from './routes/latency-heatmap'
import { Route as JvmRouteImport } from './routes/jvm'
import { Route as InfraRouteImport } from './routes/infra'
import { Route as HistogramRouteImport } from './routes/histogram'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DbQueriesRouteImport } from './routes/db-queries'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CausalityRouteImport } from './routes/causality'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CardinalityRouteImport } from './routes/cardinality'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiopsRouteImport } from './routes/aiops'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesNameRouteImport } from './routes/services.$name'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceCompareRoute = TraceCompareRouteImport.update({
  id: '/trace-compare',
  path: '/trace-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const TopMoversRoute = TopMoversRouteImport.update({
  id: '/top-movers',
  path: '/top-movers',
  getParentRoute: () => rootRouteImport,
} as any)
const SlowSpansRoute = SlowSpansRouteImport.update({
  id: '/slow-spans',
  path: '/slow-spans',
  getParentRoute: () => rootRouteImport,
} as any)
const SloRoute = SloRouteImport.update({
  id: '/slo',
  path: '/slo',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilingRoute = ProfilingRouteImport.update({
  id: '/profiling',
  path: '/profiling',
  getParentRoute: () => rootRouteImport,
} as any)
const OutliersRoute = OutliersRouteImport.update({
  id: '/outliers',
  path: '/outliers',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LatencyHeatmapRoute = LatencyHeatmapRouteImport.update({
  id: '/latency-heatmap',
  path: '/latency-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const JvmRoute = JvmRouteImport.update({
  id: '/jvm',
  path: '/jvm',
  getParentRoute: () => rootRouteImport,
} as any)
const InfraRoute = InfraRouteImport.update({
  id: '/infra',
  path: '/infra',
  getParentRoute: () => rootRouteImport,
} as any)
const HistogramRoute = HistogramRouteImport.update({
  id: '/histogram',
  path: '/histogram',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DbQueriesRoute = DbQueriesRouteImport.update({
  id: '/db-queries',
  path: '/db-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalityRoute = CausalityRouteImport.update({
  id: '/causality',
  path: '/causality',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CardinalityRoute = CardinalityRouteImport.update({
  id: '/cardinality',
  path: '/cardinality',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiopsRoute = AiopsRouteImport.update({
  id: '/aiops',
  path: '/aiops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNameRoute = ServicesNameRouteImport.update({
  id: '/services/$name',
  path: '/services/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/cardinality': typeof CardinalityRoute
  '/catalog': typeof CatalogRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/db-queries': typeof DbQueriesRoute
  '/deployments': typeof DeploymentsRoute
  '/errors': typeof ErrorsRoute
  '/forecast': typeof ForecastRoute
  '/histogram': typeof HistogramRoute
  '/infra': typeof InfraRoute
  '/jvm': typeof JvmRoute
  '/latency-heatmap': typeof LatencyHeatmapRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/outliers': typeof OutliersRoute
  '/profiling': typeof ProfilingRoute
  '/search': typeof SearchRoute
  '/slo': typeof SloRoute
  '/slow-spans': typeof SlowSpansRoute
  '/top-movers': typeof TopMoversRoute
  '/topology': typeof TopologyRoute
  '/trace-compare': typeof TraceCompareRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/cardinality': typeof CardinalityRoute
  '/catalog': typeof CatalogRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/db-queries': typeof DbQueriesRoute
  '/deployments': typeof DeploymentsRoute
  '/errors': typeof ErrorsRoute
  '/forecast': typeof ForecastRoute
  '/histogram': typeof HistogramRoute
  '/infra': typeof InfraRoute
  '/jvm': typeof JvmRoute
  '/latency-heatmap': typeof LatencyHeatmapRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/outliers': typeof OutliersRoute
  '/profiling': typeof ProfilingRoute
  '/search': typeof SearchRoute
  '/slo': typeof SloRoute
  '/slow-spans': typeof SlowSpansRoute
  '/top-movers': typeof TopMoversRoute
  '/topology': typeof TopologyRoute
  '/trace-compare': typeof TraceCompareRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aiops': typeof AiopsRoute
  '/alerts': typeof AlertsRoute
  '/cardinality': typeof CardinalityRoute
  '/catalog': typeof CatalogRoute
  '/causality': typeof CausalityRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/db-queries': typeof DbQueriesRoute
  '/deployments': typeof DeploymentsRoute
  '/errors': typeof ErrorsRoute
  '/forecast': typeof ForecastRoute
  '/histogram': typeof HistogramRoute
  '/infra': typeof InfraRoute
  '/jvm': typeof JvmRoute
  '/latency-heatmap': typeof LatencyHeatmapRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/outliers': typeof OutliersRoute
  '/profiling': typeof ProfilingRoute
  '/search': typeof SearchRoute
  '/slo': typeof SloRoute
  '/slow-spans': typeof SlowSpansRoute
  '/top-movers': typeof TopMoversRoute
  '/topology': typeof TopologyRoute
  '/trace-compare': typeof TraceCompareRoute
  '/traces': typeof TracesRoute
  '/services/$name': typeof ServicesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aiops'
    | '/alerts'
    | '/cardinality'
    | '/catalog'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/db-queries'
    | '/deployments'
    | '/errors'
    | '/forecast'
    | '/histogram'
    | '/infra'
    | '/jvm'
    | '/latency-heatmap'
    | '/live'
    | '/logs'
    | '/metrics'
    | '/outliers'
    | '/profiling'
    | '/search'
    | '/slo'
    | '/slow-spans'
    | '/top-movers'
    | '/topology'
    | '/trace-compare'
    | '/traces'
    | '/services/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aiops'
    | '/alerts'
    | '/cardinality'
    | '/catalog'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/db-queries'
    | '/deployments'
    | '/errors'
    | '/forecast'
    | '/histogram'
    | '/infra'
    | '/jvm'
    | '/latency-heatmap'
    | '/live'
    | '/logs'
    | '/metrics'
    | '/outliers'
    | '/profiling'
    | '/search'
    | '/slo'
    | '/slow-spans'
    | '/top-movers'
    | '/topology'
    | '/trace-compare'
    | '/traces'
    | '/services/$name'
  id:
    | '__root__'
    | '/'
    | '/aiops'
    | '/alerts'
    | '/cardinality'
    | '/catalog'
    | '/causality'
    | '/compare'
    | '/dashboard'
    | '/db-queries'
    | '/deployments'
    | '/errors'
    | '/forecast'
    | '/histogram'
    | '/infra'
    | '/jvm'
    | '/latency-heatmap'
    | '/live'
    | '/logs'
    | '/metrics'
    | '/outliers'
    | '/profiling'
    | '/search'
    | '/slo'
    | '/slow-spans'
    | '/top-movers'
    | '/topology'
    | '/trace-compare'
    | '/traces'
    | '/services/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiopsRoute: typeof AiopsRoute
  AlertsRoute: typeof AlertsRoute
  CardinalityRoute: typeof CardinalityRoute
  CatalogRoute: typeof CatalogRoute
  CausalityRoute: typeof CausalityRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  DbQueriesRoute: typeof DbQueriesRoute
  DeploymentsRoute: typeof DeploymentsRoute
  ErrorsRoute: typeof ErrorsRoute
  ForecastRoute: typeof ForecastRoute
  HistogramRoute: typeof HistogramRoute
  InfraRoute: typeof InfraRoute
  JvmRoute: typeof JvmRoute
  LatencyHeatmapRoute: typeof LatencyHeatmapRoute
  LiveRoute: typeof LiveRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  OutliersRoute: typeof OutliersRoute
  ProfilingRoute: typeof ProfilingRoute
  SearchRoute: typeof SearchRoute
  SloRoute: typeof SloRoute
  SlowSpansRoute: typeof SlowSpansRoute
  TopMoversRoute: typeof TopMoversRoute
  TopologyRoute: typeof TopologyRoute
  TraceCompareRoute: typeof TraceCompareRoute
  TracesRoute: typeof TracesRoute
  ServicesNameRoute: typeof ServicesNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace-compare': {
      id: '/trace-compare'
      path: '/trace-compare'
      fullPath: '/trace-compare'
      preLoaderRoute: typeof TraceCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-movers': {
      id: '/top-movers'
      path: '/top-movers'
      fullPath: '/top-movers'
      preLoaderRoute: typeof TopMoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slow-spans': {
      id: '/slow-spans'
      path: '/slow-spans'
      fullPath: '/slow-spans'
      preLoaderRoute: typeof SlowSpansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slo': {
      id: '/slo'
      path: '/slo'
      fullPath: '/slo'
      preLoaderRoute: typeof SloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiling': {
      id: '/profiling'
      path: '/profiling'
      fullPath: '/profiling'
      preLoaderRoute: typeof ProfilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outliers': {
      id: '/outliers'
      path: '/outliers'
      fullPath: '/outliers'
      preLoaderRoute: typeof OutliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latency-heatmap': {
      id: '/latency-heatmap'
      path: '/latency-heatmap'
      fullPath: '/latency-heatmap'
      preLoaderRoute: typeof LatencyHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jvm': {
      id: '/jvm'
      path: '/jvm'
      fullPath: '/jvm'
      preLoaderRoute: typeof JvmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra': {
      id: '/infra'
      path: '/infra'
      fullPath: '/infra'
      preLoaderRoute: typeof InfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histogram': {
      id: '/histogram'
      path: '/histogram'
      fullPath: '/histogram'
      preLoaderRoute: typeof HistogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-queries': {
      id: '/db-queries'
      path: '/db-queries'
      fullPath: '/db-queries'
      preLoaderRoute: typeof DbQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causality': {
      id: '/causality'
      path: '/causality'
      fullPath: '/causality'
      preLoaderRoute: typeof CausalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardinality': {
      id: '/cardinality'
      path: '/cardinality'
      fullPath: '/cardinality'
      preLoaderRoute: typeof CardinalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aiops': {
      id: '/aiops'
      path: '/aiops'
      fullPath: '/aiops'
      preLoaderRoute: typeof AiopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$name': {
      id: '/services/$name'
      path: '/services/$name'
      fullPath: '/services/$name'
      preLoaderRoute: typeof ServicesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiopsRoute: AiopsRoute,
  AlertsRoute: AlertsRoute,
  CardinalityRoute: CardinalityRoute,
  CatalogRoute: CatalogRoute,
  CausalityRoute: CausalityRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  DbQueriesRoute: DbQueriesRoute,
  DeploymentsRoute: DeploymentsRoute,
  ErrorsRoute: ErrorsRoute,
  ForecastRoute: ForecastRoute,
  HistogramRoute: HistogramRoute,
  InfraRoute: InfraRoute,
  JvmRoute: JvmRoute,
  LatencyHeatmapRoute: LatencyHeatmapRoute,
  LiveRoute: LiveRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  OutliersRoute: OutliersRoute,
  ProfilingRoute: ProfilingRoute,
  SearchRoute: SearchRoute,
  SloRoute: SloRoute,
  SlowSpansRoute: SlowSpansRoute,
  TopMoversRoute: TopMoversRoute,
  TopologyRoute: TopologyRoute,
  TraceCompareRoute: TraceCompareRoute,
  TracesRoute: TracesRoute,
  ServicesNameRoute: ServicesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
